taskset -c 3-7 ./run_kernel trace/profile_cnn_history_0.stats ./tinfo/DAG_1/node_2:2_3 0 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_1.stats ./tinfo/DAG_1/node_2:2_3 1 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_2.stats ./tinfo/DAG_1/node_0:0 2 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_3.stats ./tinfo/DAG_1/node_0:0 3 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_4.stats ./tinfo/DAG_1/node_1:1 4 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_5.stats ./tinfo/DAG_1/node_1:1 5 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_6.stats ./tinfo/DAG_1/node_0:0_1_2 6 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_7.stats ./tinfo/DAG_1/node_0:0_1_2 7 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_8.stats ./tinfo/DAG_1/node_0:0_1_2_3 8 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_9.stats ./tinfo/DAG_1/node_0:0_1_2_3 9 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_10.stats ./tinfo/DAG_1/node_0:0_1 10 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_11.stats ./tinfo/DAG_1/node_0:0_1 11 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_12.stats ./tinfo/DAG_1/node_0:0_1_2_3_4 12 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_13.stats ./tinfo/DAG_1/node_0:0_1_2_3_4 13 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_14.stats ./tinfo/DAG_1/node_2:2 14 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_15.stats ./tinfo/DAG_1/node_2:2 15 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_16.stats ./tinfo/DAG_1/node_1:1_2_3 16 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_17.stats ./tinfo/DAG_1/node_1:1_2_3 17 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_18.stats ./tinfo/DAG_1/node_1:1_2_3_4 18 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_19.stats ./tinfo/DAG_1/node_1:1_2_3_4 19 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_20.stats ./tinfo/DAG_1/node_2:2_3_4_5 20 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_21.stats ./tinfo/DAG_1/node_2:2_3_4_5 21 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_22.stats ./tinfo/DAG_1/node_3:3_4_5 22 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_23.stats ./tinfo/DAG_1/node_3:3_4_5 23 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_24.stats ./tinfo/DAG_1/node_1:1_2_3_4_5 24 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_25.stats ./tinfo/DAG_1/node_1:1_2_3_4_5 25 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_26.stats ./tinfo/DAG_1/node_3:3 26 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_27.stats ./tinfo/DAG_1/node_3:3 27 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_28.stats ./tinfo/DAG_1/node_5:5 28 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_29.stats ./tinfo/DAG_1/node_5:5 29 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_30.stats ./tinfo/DAG_1/node_4:4 30 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_31.stats ./tinfo/DAG_1/node_4:4 31 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_32.stats ./tinfo/DAG_1/node_1:1_2 32 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_33.stats ./tinfo/DAG_1/node_1:1_2 33 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_34.stats ./tinfo/DAG_1/node_3:3_4 34 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_35.stats ./tinfo/DAG_1/node_3:3_4 35 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_36.stats ./tinfo/DAG_1/node_2:2_3_4 36 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_37.stats ./tinfo/DAG_1/node_2:2_3_4 37 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_38.stats ./tinfo/DAG_1/node_4:4_5 38 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_39.stats ./tinfo/DAG_1/node_4:4_5 39 0 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_40.stats ./tinfo/DAG_1/node_0:0_1_2_3_4_5 40 1 ./dag_history/dag_history_1.stats
taskset -c 3-7 ./run_kernel trace/profile_cnn_history_41.stats ./tinfo/DAG_1/node_0:0_1_2_3_4_5 41 0 ./dag_history/dag_history_1.stats

